package com.elsevier.bts.regional.ecom.framework.base;

public enum BrowserType {
    Firefox_Local,
    Firefox_Local_ZAP,
    Firefox_Zalenium,
    OSX_Firefox_CBT,
    OSX_Firefox_LT,
    OSX_Firefox_BS,
    Chrome_Local,
    Chrome_Local_Mobile,
    Chrome_Local_Headless,
    Chrome_Local_ZAP,
    Chrome_Zalenium,
    Win10_Chrome_CBT,
    Win10_Chrome_LT,
    Win11_Chrome_BS,
    Win10_Chrome_LT_Visual,
    OSX_Chrome_LT_perf,
    Win10_IE_CBT,
    Win10_IE_LT,
    IE_BS,
    OSX_Safari_CBT,
    OSX_Safari_LT,
    Safari_Local,
    Win10_Edge_CBT,
    Win10_Edge_LT,
    Edge_BS,
    Edge_Local,
    iOS_Safari_CBT,
    iOS_Safari_LT,
    Android_Chrome_CBT,
    Android_Chrome_LT,
    Android_Chrome_Local,
    Android_Chrome_BS,
    Ios_Chrome_BS
}
