name: Run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
#    runs-on:
#      group: elsevier-standard-runners
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: npm install
        run: |
          npm install
      - name: run Lighthouse CI
        run: |
          npm run lhci
# THE FOLLOWING NEEDS IAW APPROVAL BEFORE IT CAN BE USED
#      - name: Audit URLs using Lighthouse
#        uses: treosh/lighthouse-ci-action@v10
